### ISSUE TITLE
How to use python write the evaluation function of CMC and mAP for SYSU-MM01 like evaluate Market1501? 

### ISSUE THREAD

**Issue by zengsmallqiang** [sshkhr/cmGAN#1]
the link of  evaluation codes of Market1501 :https://github.com/Cysu/open-reid/blob/master/reid/evaluation_metrics/ranking.py

**Comment by sshkhr** [comment]
Hi @zengsmallqiang 

I will add evaluation code for SYSU-MM01 soon. I was a little busy with graduate school applications and couldn't update. Thanks for pointing out

**Comment by sshkhr** [comment]
I have added the evaluation code SYSU in the format as Market-1501. Note that this is single shot only

I am closing this issue. Please feel free to re-open it if I haven't added the final code before November end.
