### ISSUE TITLE
No such file or directory: saved/feature_generator_0.pth

### ISSUE THREAD

**Issue by absagargupta** [sshkhr/cmGAN#6]
Hello there. 
I am running into the following error right after the first epoch.

Epoch 001/025 [40567/40568] -- loss_G: 51092299776.0000 | loss_D:
269421216.0000 | loss_triplet_rgb: 6807528960.0000 | triplet_loss_ir:
355213632.0000 | loss_identity: 43929559040.0000 | loss_total:
-51078832128.0000 -- ETA: 5 days, 3:48:27.218331--TEpoch 001/025
[40568/40568] -- loss_G: 51091042304.0000 | loss_D: 269414592.0000 |
loss_triplet_rgb: 6807361536.0000 | triplet_loss_ir: 355204864.0000 |
loss_identity: 43928477696.0000 | loss_total: -51077570560.0000 --
ETA: 5 days, 3:48:25.683334--Time in Epoch : 5:09:31.070139
Extracted features for query set, obtained 99-by-2048 matrix
Extracted features for gallery set, obtained 1974-by-2048 matrix
Computing CMC and mAP
Query ID 334
Gallery ID Rank # 0  :  334 distance :  0.0
Gallery ID Rank # 1  :  401 distance :  0.0
Gallery ID Rank # 2  :  401 distance :  0.0
Gallery ID Rank # 3  :  401 distance :  0.0
Gallery ID Rank # 4  :  401 distance :  0.0
Gallery ID Rank # 5  :  401 distance :  0.0
Gallery ID Rank # 6  :  401 distance :  0.0
Gallery ID Rank # 7  :  401 distance :  0.0
Gallery ID Rank # 8  :  401 distance :  0.0
Gallery ID Rank # 9  :  401 distance :  0.0
Gallery ID Rank # 10  :  401 distance :  0.0
Gallery ID Rank # 11  :  401 distance :  0.0
Gallery ID Rank # 12  :  401 distance :  0.0
Gallery ID Rank # 13  :  401 distance :  0.0
Gallery ID Rank # 14  :  401 distance :  0.0
Gallery ID Rank # 15  :  400 distance :  0.0
Gallery ID Rank # 16  :  400 distance :  0.0
Gallery ID Rank # 17  :  400 distance :  0.0
Gallery ID Rank # 18  :  400 distance :  0.0
Gallery ID Rank # 19  :  400 distance :  0.0
Results ----------
mAP: 3.0%
CMC curve
Rank-1  : 1.0%
Rank-5  : 2.0%
Rank-10 : 2.0%
Rank-20 : 3.0%
------------------
Extracted features for query set, obtained 493-by-2048 matrix
Extracted features for gallery set, obtained 20284-by-2048 matrix
Computing CMC and mAP
Query ID 1
Gallery ID Rank # 0  :  1 distance :  0.0
Gallery ID Rank # 1  :  258 distance :  0.0
Gallery ID Rank # 2  :  258 distance :  0.0
Gallery ID Rank # 3  :  258 distance :  0.0
Gallery ID Rank # 4  :  258 distance :  0.0
Gallery ID Rank # 5  :  258 distance :  0.0
Gallery ID Rank # 6  :  258 distance :  0.0
Gallery ID Rank # 7  :  258 distance :  0.0
Gallery ID Rank # 8  :  258 distance :  0.0
Gallery ID Rank # 9  :  258 distance :  0.0
Gallery ID Rank # 10  :  258 distance :  0.0
Gallery ID Rank # 11  :  258 distance :  0.0
Gallery ID Rank # 12  :  258 distance :  0.0
Gallery ID Rank # 13  :  258 distance :  0.0
Gallery ID Rank # 14  :  258 distance :  0.0
Gallery ID Rank # 15  :  258 distance :  0.0
Gallery ID Rank # 16  :  258 distance :  0.0
Gallery ID Rank # 17  :  258 distance :  0.0
Gallery ID Rank # 18  :  258 distance :  0.0
Gallery ID Rank # 19  :  258 distance :  0.0
Results ----------
mAP: 1.3%
CMC curve
Rank-1  : 0.4%
Rank-5  : 0.8%
Rank-10 : 0.8%
Rank-20 : 0.8%
------------------

Traceback (most recent call last):
  File "train.py", line 192, in <module>
    torch.save(feature_generator.state_dict(),
'saved/feature_generator_'+str(epoch)+'.pth')
  File "/home/sagar18174/.conda/envs/AI3/lib/python3.6/site-packages/torch/serialization.py",
line 161, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f,
pickle_module, pickle_protocol))
  File "/home/sagar18174/.conda/envs/AI3/lib/python3.6/site-packages/torch/serialization.py",
line 116, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory:
'saved/feature_generator_0.pth'

It appears there is no such file at the provided location

Any help will be highly appreciated

Sagar

**Comment by absagargupta** [comment]
If anyone is encountering such an error. Do the following

Make a folder namely saved in the cmgan-master folder.

**Comment by sshkhr** [comment]
I will edit the code to create the folder if it doesn't exist. Thanks for pointing this out
